### ISSUE TITLE
Uncontrolled automatic opening of countless panes

### ISSUE THREAD

**Issue by Hunanbean** [jsartelle/obsidian-auto-split#3]
Some sort of loop allowed countless windows to open when opening a video from the vault. This is an uncommon issue, but severe. I was only able to close the multiple windows becuase i alt-f4ed out of the program when it hit about 50 windows. I had to spread the program across multiple screens to get an X so i could close the windows. (There may be a shortcut to close a pane, but i did not know it at the time.

May be reproducable by:
Having the extended media plugin enabled and auto-split enabled. 
Open a video file from the vault, on its own, not inside of a note. see how it open two panes. 
open a note. see three panes are open. open another note, see four panes are open.
Disable the extened media plugin. 
click a video in the vault. watch the panes start opening, several per second. 

In case anyone else experiences this issue, the shortcut to close active pane is ctrl-w

**Comment by jsartelle** [comment]
This should be fixed in 1.1.1.
