### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by huyz** [jsartelle/obsidian-auto-split#5]
This has never worked for me.  I've tried restarting, re-enabling, reinstalling it.
Nothing works.

Any idea of how I can debug this?

**Comment by jsartelle** [comment]
Can you see if you get any errors in the console when you install or enable it? Press Ctrl+Alt+I or Cmd+Alt+I and click the Console tab at the top.

Also make sure your Obsidian version is at least 0.12.19, and that your window size is wider than the Minimum Size in the plugin options.

**Comment by huyz** [comment]
No errors and I checked all the other things. There must be some conflict with another plugin.  I run a ton of plugins. Maybe I'll figure it out some day

**Comment by jsartelle** [comment]
One other question, what platform are you on? I've only tested on Mac, Windows and iOS. I can't see why it would matter, but who knows ¯\_(ツ)_/¯

**Comment by huyz** [comment]
I'm on macOS 12 Monterey.
I'm pretty sure it'll be some plugin conflict
