### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by matilde-t** [jsartelle/obsidian-auto-split#6]
Hi, I'm using Obsidian Flatpak 1.1.15 and this plugin in version 1.1.2, but it doesn't work

- I don't have any other plugin (I'm quite new to Obsidian)
- I tried opening and closing the app, reloading the plugin, changing the minimum split size, but I cannot make it work

Edit: that was on PopOS 22.04 (Ubuntu based), now I'm trying on EndeavourOS (Arch based) with the community package and it works, so I guess it has something to do with Flatpak?

**Comment by jsartelle** [comment]
Hello! Sorry for the late response :) Just wanted to thank you for investigating. I've heard from multiple sources that Flatpak Obsidian has some issues.
