### ISSUE TITLE
Feature Request: Add Command to Split and Link currently open note

### ISSUE THREAD

**Issue by TheMathGuyd** [jsartelle/obsidian-auto-split#9]
While Obsidian default provide Split Right and Split Down, they ruse to add a command accesible via hotkey to split and link a note. Your plugin is able to split&link a note on open, and I wonder if you can adapt it for this function to be accessible on files already open. Thank you for considering

**Comment by jsartelle** [comment]
Good idea! I've added this in version 1.2.
